import React, { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'zh' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations = {
  zh: {
    // Navigation
    'nav.chat': '聊天',
    'nav.image': '图片', 
    'nav.video': '视频',
    'nav.voice': '语音',
    'nav.upgrade': '升级',
    
    // Main content
    'main.welcome': '欢迎使用 MetaDIA',
    'main.subtitle': '您可以开始一个新的对话，或者尝试以下建议：',
    'main.research': '垂类研究',
    
    // Feature cards
    'feature.report.title': '如何做数据报表',
    'feature.report.desc': '学习如何创建专业的数据分析报表',
    'feature.news.title': '如何获取到最新的资讯',
    'feature.news.desc': '掌握获取实时信息的技巧和方法',
    'feature.guide.title': '如何学习指导手册',
    'feature.guide.desc': '快速上手使用指南和最佳实践',
    
    // Input
    'input.placeholder': '发送消息...',
    
    // Language switch
    'lang.chinese': '中文',
    'lang.english': 'English',
    
    // Select options
    'select.tech': '技术研究',
    'select.business': '商业分析',
    
    // Image Interface
    'image.title': 'AI图片生成',
    'image.subtitle': '把你的奇思妙想变成画！',
    'image.style': '生成风格',
    'image.size': '图片尺寸',
    'image.prompt': '描述您想要的图片',
    'image.prompt.placeholder': '✨ 例如：画一只在图书馆里打瞌睡的熊猫',
    'image.generated': '生成的图片',
    'image.upload.title': '上传图片进行编辑',
    'image.upload.desc': '拖进来一张图，我们帮你变身！',
    'image.upload.select': '选择文件',
    'image.styles.realistic': '写实风格',
    'image.styles.anime': '动漫风格',
    'image.styles.painting': '油画风格',
    'image.styles.sketch': '素描风格',
    'image.styles.digital': '数字艺术',
    'image.styles.watercolor': '水彩风格',
    'image.sizes.square': '正方形 (1:1)',
    'image.sizes.landscape': '横向 (16:9)',
    'image.sizes.portrait': '纵向 (9:16)',
    
    // New Image Interface elements
    'image.modes.text2img': '文字生成图',
    'image.modes.img2img': '图生图',
    'image.modes.voice': '语音描述',
    'image.modes.sketch': '草图涂鸦',
    'image.ai.prompt': 'AI提示',
    'image.size.small': '小',
    'image.size.medium': '中',
    'image.size.large': '大',
    'image.remix': 'Remix',
    'image.share': '分享',
    'image.generating': '正在创作中...',
    
    // Video Interface
    'video.title': 'AI一键拍大片',
    'video.subtitle': '把你的点子变成酷炫视频！',
    'video.style': '视频风格',
    'video.resolution': '分辨率',
    'video.framerate': '帧率',
    'video.duration': '视频时长',
    'video.prompt': '描述您想要的视频',
    'video.prompt.placeholder': '✨ 比如：在操场上打篮球的动漫少年，夕阳下超燃！',
    'video.generated': '生成的视频',
    'video.upload.title': '上传视频进行编辑',
    'video.upload.desc': '拖进来你的视频，AI帮你变魔法 🎬',
    'video.upload.select': '选择文件',
    'video.styles.cinematic': '电影风格',
    'video.styles.animation': '动画风格',
    'video.styles.documentary': '纪录片风格',
    'video.styles.music-video': '音乐视频',
    'video.styles.commercial': '广告风格',
    'video.styles.artistic': '艺术风格',
    'video.generate': '开始拍摄',
    
    // New Video Interface elements
    'video.modes.text2video': '文字生成视频',
    'video.modes.voice2video': '语音描述',
    'video.modes.script': '分镜脚本',
    'video.modes.template': '视频模版',
    'video.keywords': '关键词标签',
    'video.templates.campus': '校园日常',
    'video.templates.anime': '二次元风',
    'video.templates.scifi': '科幻未来',
    'video.templates.romance': '浪漫温馨',
    'video.templates.comedy': '搞笑幽默',
    'video.templates.dance': '舞蹈音乐',
    'video.quality.fast': '快出片',
    'video.quality.clear': '清晰',
    'video.quality.ultra': '超清大片',
    'video.platform.tiktok': '适合抖音',
    'video.platform.bilibili': '适合B站',
    'video.platform.xiaohongshu': '适合小红书',
    'video.challenge.today': '今日挑战',
    'video.challenge.desc': '生成一条10秒科幻校园视频',
    'video.ai.prompt': 'AI提示',
    'video.voice.record': '语音描述',
    'video.script.add': '添加分镜',
    'video.preview': '预览关键帧',
    'video.generating': '正在拍摄中...',
    'video.style.tag': 'AI风格标签',
    'video.script.title': '分镜脚本',
    'video.script.placeholder': '描述这个场景...',
    'video.scene': '场景',
    'video.recording': '正在录音中...',
    'video.voice.instruction': '点击开始语音描述你想要的视频',
    'video.duration.seconds': '秒',
    'video.quality.info': '1080p • 30fps',
    'video.keywords.campus': '校园',
    'video.keywords.youth': '青春',
    'video.keywords.friendship': '友情',
    'video.keywords.dream': '梦想',
    'video.keywords.technology': '科技',
    'video.keywords.future': '未来',
    'video.keywords.warm': '温馨',
    'video.keywords.funny': '搞笑',
    'video.keywords.inspiring': '励志',
    'video.keywords.romantic': '浪漫',
    'video.keywords.adventure': '冒险',
    'video.keywords.growth': '成长',
    'video.templates.campus.desc': '校园日常生活场景',
    'video.templates.anime.desc': '二次元动漫风格',
    'video.templates.scifi.desc': '科幻未来世界',
    'video.templates.romance.desc': '浪漫温馨氛围',
    'video.templates.comedy.desc': '搞笑幽默内容',
    'video.templates.dance.desc': '舞蹈音乐视频',
    'video.ai.style.cyberpunk': '赛博朋克导演',
    'video.script.timeline': '时间轴',
    'video.script.description': '场景描述',
    'video.script.camera': '镜头角度',
    'video.script.audio': '音频描述',
    'video.script.duration.label': '时长',
    'video.script.remove': '删除场景',
    'video.script.move-up': '上移',
    'video.script.move-down': '下移',
    'video.script.preview.keyframe': '预览关键帧',
    'video.script.camera.close': '特写',
    'video.script.camera.medium': '中景',
    'video.script.camera.wide': '远景',
    'video.script.camera.overhead': '俯视',
    'video.script.camera.lowangle': '仰视',
    'video.script.camera.handheld': '手持',
    
    // 认证相关
    'auth.login': '登录',
    'auth.signup': '注册',
    'auth.logout': '退出登录',
    'auth.welcome.back': '欢迎回来',
    'auth.join.us': '加入MetaDIA',
    'auth.email': '邮箱',
    'auth.password': '密码',
    'auth.confirm.password': '确认密码',
    'auth.phone': '手机号',
    'auth.login.email': '邮箱登录',
    'auth.login.phone': '手机登录',
    'auth.login.google': '使用Google登录',
    'auth.login.github': '使用GitHub登录',
    'auth.login.metamask': '使用MetaMask登录',
    'auth.forgot.password': '忘记密码？',
    'auth.no.account': '还没有账号？',
    'auth.have.account': '已有账号？',
    'auth.register.now': '立即注册',
    'auth.login.now': '立即登录',
    'auth.or': '或',
    'auth.continue.with': '使用以下方式继续',
    'auth.metamask.connect': '连接MetaMask钱包',
    'auth.metamask.not.installed': '请先安装MetaMask钱包',
    'auth.metamask.connecting': '正在连接...',
    'auth.sms.code': '短信验证码',
    'auth.send.code': '发送验证码',
    'auth.verify.code': '验证码',
    'auth.email.placeholder': '请��入邮箱地址',
    'auth.password.placeholder': '请输入密码',
    'auth.phone.placeholder': '请输入手机号',
    'auth.code.placeholder': '请输入验证码',
    'auth.signing.in': '登录中...',
    'auth.signing.up': '注册中...',
    'auth.profile': '个人资料',
    'auth.settings': '设置',
    'auth.user.center': '用户中心',
    'auth.name.placeholder': '姓名（选填）',
    'auth.fill.email.password': '请填写邮箱和密码',
    'auth.password.min.length': '密码至少需要6位',
    'auth.login.failed': '登录失败',
    'auth.login.success': '登录成功！',
    'auth.auto.register.hint': '如果是新用户，系统会自动为您创建账户',
    'auth.smart.login.hint': '智能登录：已有账户直接登录，新用户自动注册',
    
    // Voice Interface
    'voice.title': 'AI语音生成',
    'voice.subtitle': '将文字转换为自然流畅的语音',
    'voice.select': '选择声音',
    'voice.language': '语言',
    'voice.speed': '语速',
    'voice.pitch': '音调',
    'voice.text': '输入要转换的文本',
    'voice.text.placeholder': '在这里输入您想要转换为语音的文本...',
    'voice.record.start': '开始录音',
    'voice.record.stop': '停止录音',
    'voice.generate': '生成语音',
    'voice.generated': '生成的语音',
    'voice.upload.title': '上传音频进行处理',
    'voice.upload.desc': '支持 MP3、WAV、M4A 格式，最大 50MB',
    'voice.upload.select': '选择文件',
    'voice.voices.female-1': '女声 - 温柔',
    'voice.voices.female-2': '女声 - 活泼',
    'voice.voices.male-1': '男声 - 磁性',
    'voice.voices.male-2': '男声 - 沉稳',
    'voice.voices.child': '童声 - 可爱',
    'voice.voices.elderly': '长者 - 慈祥',
    'voice.languages.zh-cn': '中文(普通话)',
    'voice.languages.en-us': 'English (US)',
    'voice.languages.ja-jp': '日本語',
    'voice.languages.ko-kr': '한국어',
    'voice.languages.fr-fr': 'Français',
    'voice.languages.de-de': 'Deutsch'
  },
  en: {
    // Navigation
    'nav.chat': 'Chat',
    'nav.image': 'Image',
    'nav.video': 'Video', 
    'nav.voice': 'Voice',
    'nav.upgrade': 'Upgrade',
    
    // Main content
    'main.welcome': 'Welcome to MetaDIA',
    'main.subtitle': 'You can start a new conversation or try the following suggestions:',
    'main.research': 'Vertical Research',
    
    // Feature cards
    'feature.report.title': 'How to create data reports',
    'feature.report.desc': 'Learn how to create professional data analysis reports',
    'feature.news.title': 'How to get the latest information',
    'feature.news.desc': 'Master the skills and methods of obtaining real-time information',
    'feature.guide.title': 'How to learn instruction manual',
    'feature.guide.desc': 'Quick start guide and best practices',
    
    // Input
    'input.placeholder': 'Send message...',
    
    // Language switch
    'lang.chinese': '中文',
    'lang.english': 'English',
    
    // Select options
    'select.tech': 'Technology Research',
    'select.business': 'Business Analysis',
    
    // Image Interface
    'image.title': 'AI Image Generation',
    'image.subtitle': 'Turn your wild ideas into amazing art!',
    'image.style': 'Generation Style',
    'image.size': 'Image Size',
    'image.prompt': 'Describe the image you want',
    'image.prompt.placeholder': '✨ e.g., Draw a panda sleeping in a library',
    'image.generated': 'Generated Images',
    'image.upload.title': 'Upload Image for Editing',
    'image.upload.desc': 'Drag an image here and we\'ll transform it!',
    'image.upload.select': 'Choose File',
    'image.styles.realistic': 'Realistic Style',
    'image.styles.anime': 'Anime Style',
    'image.styles.painting': 'Oil Painting Style',
    'image.styles.sketch': 'Sketch Style',
    'image.styles.digital': 'Digital Art',
    'image.styles.watercolor': 'Watercolor Style',
    'image.sizes.square': 'Square (1:1)',
    'image.sizes.landscape': 'Landscape (16:9)',
    'image.sizes.portrait': 'Portrait (9:16)',
    
    // New Image Interface elements
    'image.modes.text2img': 'Text to Image',
    'image.modes.img2img': 'Image to Image',
    'image.modes.voice': 'Voice Description',
    'image.modes.sketch': 'Sketch Drawing',
    'image.ai.prompt': 'AI Prompt',
    'image.size.small': 'Small',
    'image.size.medium': 'Medium',
    'image.size.large': 'Large',
    'image.remix': 'Remix',
    'image.share': 'Share',
    'image.generating': 'Creating magic...',
    
    // Video Interface
    'video.title': 'AI Blockbuster Maker',
    'video.subtitle': 'Turn your ideas into amazing videos!',
    'video.style': 'Video Style',
    'video.resolution': 'Resolution',
    'video.framerate': 'Frame Rate',
    'video.duration': 'Video Duration',
    'video.prompt': 'Describe the video you want',
    'video.prompt.placeholder': '✨ e.g., Anime boy playing basketball on campus at sunset, super cool!',
    'video.generated': 'Generated Videos',
    'video.upload.title': 'Upload Video for Editing',
    'video.upload.desc': 'Drag your video here and we\'ll work magic! 🎬',
    'video.upload.select': 'Choose File',
    'video.styles.cinematic': 'Cinematic Style',
    'video.styles.animation': 'Animation Style',
    'video.styles.documentary': 'Documentary Style',
    'video.styles.music-video': 'Music Video',
    'video.styles.commercial': 'Commercial Style',
    'video.styles.artistic': 'Artistic Style',
    'video.generate': 'Start Filming',
    
    // New Video Interface elements
    'video.modes.text2video': 'Text to Video',
    'video.modes.voice2video': 'Voice Description',
    'video.modes.script': 'Storyboard Script',
    'video.modes.template': 'Video Templates',
    'video.keywords': 'Keyword Tags',
    'video.templates.campus': 'Campus Life',
    'video.templates.anime': 'Anime Style',
    'video.templates.scifi': 'Sci-Fi Future',
    'video.templates.romance': 'Romantic',
    'video.templates.comedy': 'Comedy Fun',
    'video.templates.dance': 'Dance & Music',
    'video.quality.fast': 'Fast',
    'video.quality.clear': 'Clear',
    'video.quality.ultra': 'Ultra HD',
    'video.platform.tiktok': 'For TikTok',
    'video.platform.bilibili': 'For Bilibili',
    'video.platform.xiaohongshu': 'For XiaoHongShu',
    'video.challenge.today': 'Daily Challenge',
    'video.challenge.desc': 'Create a 10-second sci-fi campus video',
    'video.ai.prompt': 'AI Prompt',
    'video.voice.record': 'Voice Description',
    'video.script.add': 'Add Scene',
    'video.preview': 'Preview Keyframes',
    'video.generating': 'Filming in progress...',
    'video.style.tag': 'AI Style Tag',
    'video.script.title': 'Storyboard Script',
    'video.script.placeholder': 'Describe this scene...',
    'video.scene': 'Scene',
    'video.recording': 'Recording...',
    'video.voice.instruction': 'Click to start voice description of your desired video',
    'video.duration.seconds': 'sec',
    'video.quality.info': '1080p • 30fps',
    'video.keywords.campus': 'Campus',
    'video.keywords.youth': 'Youth',
    'video.keywords.friendship': 'Friendship',
    'video.keywords.dream': 'Dream',
    'video.keywords.technology': 'Tech',
    'video.keywords.future': 'Future',
    'video.keywords.warm': 'Warm',
    'video.keywords.funny': 'Funny',
    'video.keywords.inspiring': 'Inspiring',
    'video.keywords.romantic': 'Romantic',
    'video.keywords.adventure': 'Adventure',
    'video.keywords.growth': 'Growth',
    'video.templates.campus.desc': 'Campus daily life scenes',
    'video.templates.anime.desc': 'Anime style',
    'video.templates.scifi.desc': 'Sci-fi future world',
    'video.templates.romance.desc': 'Romantic atmosphere',
    'video.templates.comedy.desc': 'Comedy content',
    'video.templates.dance.desc': 'Dance music videos',
    'video.ai.style.cyberpunk': 'Cyberpunk Director',
    'video.script.timeline': 'Timeline',
    'video.script.description': 'Scene Description',
    'video.script.camera': 'Camera Angle',
    'video.script.audio': 'Audio Description',
    'video.script.duration.label': 'Duration',
    'video.script.remove': 'Remove Scene',
    'video.script.move-up': 'Move Up',
    'video.script.move-down': 'Move Down',
    'video.script.preview.keyframe': 'Preview Keyframe',
    'video.script.camera.close': 'Close-up',
    'video.script.camera.medium': 'Medium Shot',
    'video.script.camera.wide': 'Wide Shot',
    'video.script.camera.overhead': 'Overhead',
    'video.script.camera.lowangle': 'Low Angle',
    'video.script.camera.handheld': 'Handheld',
    
    // Authentication
    'auth.login': 'Login',
    'auth.signup': 'Sign Up',
    'auth.logout': 'Logout',
    'auth.welcome.back': 'Welcome Back',
    'auth.join.us': 'Join MetaDIA',
    'auth.email': 'Email',
    'auth.password': 'Password',
    'auth.confirm.password': 'Confirm Password',
    'auth.phone': 'Phone Number',
    'auth.login.email': 'Email Login',
    'auth.login.phone': 'Phone Login',
    'auth.login.google': 'Continue with Google',
    'auth.login.github': 'Continue with GitHub',
    'auth.login.metamask': 'Connect with MetaMask',
    'auth.forgot.password': 'Forgot password?',
    'auth.no.account': "Don't have an account?",
    'auth.have.account': 'Already have an account?',
    'auth.register.now': 'Sign up now',
    'auth.login.now': 'Login now',
    'auth.or': 'or',
    'auth.continue.with': 'Continue with',
    'auth.metamask.connect': 'Connect MetaMask Wallet',
    'auth.metamask.not.installed': 'Please install MetaMask first',
    'auth.metamask.connecting': 'Connecting...',
    'auth.sms.code': 'SMS Code',
    'auth.send.code': 'Send Code',
    'auth.verify.code': 'Verification Code',
    'auth.email.placeholder': 'Enter your email',
    'auth.password.placeholder': 'Enter your password',
    'auth.phone.placeholder': 'Enter your phone number',
    'auth.code.placeholder': 'Enter verification code',
    'auth.signing.in': 'Signing in...',
    'auth.signing.up': 'Signing up...',
    'auth.profile': 'Profile',
    'auth.settings': 'Settings',
    'auth.user.center': 'User Center',
    'auth.name.placeholder': 'Name (Optional)',
    'auth.fill.email.password': 'Please fill in email and password',
    'auth.password.min.length': 'Password must be at least 6 characters',
    'auth.login.failed': 'Login failed',
    'auth.login.success': 'Login successful!',
    'auth.auto.register.hint': 'New users will be automatically registered',
    'auth.smart.login.hint': 'Smart login: existing users login directly, new users auto-register',
    
    // Voice Interface
    'voice.title': 'AI Voice Generation',
    'voice.subtitle': 'Convert text to natural, fluent speech',
    'voice.select': 'Select Voice',
    'voice.language': 'Language',
    'voice.speed': 'Speed',
    'voice.pitch': 'Pitch',
    'voice.text': 'Enter text to convert',
    'voice.text.placeholder': 'Enter the text you want to convert to speech here...',
    'voice.record.start': 'Start Recording',
    'voice.record.stop': 'Stop Recording',
    'voice.generate': 'Generate Voice',
    'voice.generated': 'Generated Audio',
    'voice.upload.title': 'Upload Audio for Processing',
    'voice.upload.desc': 'Supports MP3, WAV, M4A formats, max 50MB',
    'voice.upload.select': 'Choose File',
    'voice.voices.female-1': 'Female - Gentle',
    'voice.voices.female-2': 'Female - Lively',
    'voice.voices.male-1': 'Male - Magnetic',
    'voice.voices.male-2': 'Male - Steady',
    'voice.voices.child': 'Child - Cute',
    'voice.voices.elderly': 'Elder - Kind',
    'voice.languages.zh-cn': '中文(普通话)',
    'voice.languages.en-us': 'English (US)',
    'voice.languages.ja-jp': '日本語',
    'voice.languages.ko-kr': '한국어',
    'voice.languages.fr-fr': 'Français',
    'voice.languages.de-de': 'Deutsch'
  }
} as const;

type TranslationKey = keyof typeof translations.zh;

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('zh');
  
  const t = (key: string): string => {
    const translationKey = key as TranslationKey;
    const translation = translations[language]?.[translationKey];
    return translation || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};